function [output] = setupTrainResult(trainResult)

output = [sum(trainResult(1:4,:));sum(trainResult(5:8,:));sum(trainResult(9:12,:))...
    ;sum(trainResult(13:16,:));sum(trainResult(17:20,:))]';%;sum(trainResult(21:24,:))...
    %;sum(trainResult(25:28,:))]';
