
flexion30 = [featureExtractionMovVar(DF_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(FF_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(SF_EmgData30(start:ending,:))]

flexion50 = [featureExtractionMovVar(DF_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(FF_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(SF_EmgData50(start:ending,:))]

flexion80 = [featureExtractionMovVar(DF_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(FF_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(SF_EmgData80(start:ending,:))]

allF_Flexion = [flexion30; flexion50; flexion80];
save('allF_Flexion.mat','allF_Flexion');


extension30 = [featureExtractionMovVar(DE_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(FE_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(SE_EmgData30(start:ending,:))]

extension50 = [featureExtractionMovVar(DE_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(FE_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(SE_EmgData50(start:ending,:))]

extension80 = [featureExtractionMovVar(DE_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(FE_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(SE_EmgData80(start:ending,:))]

allF_Extension = [extension30; extension50; extension80];
save('allF_Extension.mat','allF_Extension');


ulnar30 = [featureExtractionMovVar(DU_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(FU_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(SU_EmgData30(start:ending,:))]

ulnar50 = [featureExtractionMovVar(DU_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(FU_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(SU_EmgData50(start:ending,:))]

ulnar80 = [featureExtractionMovVar(DU_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(FU_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(SU_EmgData80(start:ending,:))]

allF_Ulnar = [ulnar30; ulnar50; ulnar80];
save('allF_Ulnar.mat','allF_Ulnar');


radial30 = [featureExtractionMovVar(DR_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(FR_EmgData30(start:ending,:)); ...
    featureExtractionMovVar(SR_EmgData30(start:ending,:))]

radial50 = [featureExtractionMovVar(DR_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(FR_EmgData50(start:ending,:)); ...
    featureExtractionMovVar(SR_EmgData50(start:ending,:))]

radial80 = [featureExtractionMovVar(DR_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(FR_EmgData80(start:ending,:)); ...
    featureExtractionMovVar(SR_EmgData80(start:ending,:))]

allF_Radial = [radial30; radial50; radial80];
save('allF_Radial.mat','allF_Radial');